### PR TITLE
Add DigiCertGlobalRootG2 and MicrosoftRSARootCertificateAuthority2017…

### PR DESCRIPTION
**Pull request by RLeclair**
… as trust anchor

Adding DigiCertGlobalRoot**G2** and MicrosoftRSARootCertificateAuthority2017 as trust anchors. 
- Added .cer files to extras/TrustAnchors/
- Ran *brssl ta *.cer* on TrustAnchors folder with added certificates, added new structures to existing src/BearSSLTrustAnchors.h file

### CODE REVIEW

**Comment by RLeclair** [comment]
Hello @per1234, wanted to know what else is needed for us to move forward with merging. Thanks!

**Review by danewalton — APPROVED** [review]

**Comment by RLeclair** [comment]
Hi @per1234, wanted to check if you had the chance to look at the comment above! Is there anyone I can reach out to in order to move forward with this? Thanks!

**Comment by per1234** [comment]
Hi @RLeclair. Thanks so much for your pull request. My role in this project is janitorial in nature. I am not in a position decide about pull request merges. One of the other maintainers may be able to answer your question.

**Comment by facchinm** [comment]
Fine for me, merging :slightly_smiling_face: thx!

**Comment by RLeclair** [comment]
Thanks @facchinm :) just one more question, I saw the latest release was Aug 02, 2021. Is there a planned release date for the 1.7.3 which would include the changes here?

**Pull request merged**
